variables:
  # Use the overlay2 storage driver instead of the default "vfs" which sucks
  # https://docs.docker.com/storage/storagedriver/select-storage-driver/
  DOCKER_DRIVER: overlay2

  # When using dind service, you must instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  DOCKER_HOST: tcp://docker:2375

  # This instructs Docker not to start over TLS
  DOCKER_TLS_CERTDIR: ""

build:
  # We'll use the base Docker image for the parent container
  # Find tags here if you want specific ones:
  # https://hub.docker.com/_/docker/?tab=tags
  image: docker:latest
  stage: build
  services:
    # The child container--where we'll run this project--must use a "dind" tag
    - docker:dind
  before_script:
    # This makes sure everything's good before we build and run
    - docker info
  script:
    - docker build -t apacheep .
    - docker run -d apacheep